//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_SUPPLY_CATALOG
    {
        public int Bar_Supply_Catalog_Id { get; set; }
        public long Store_Staff_Id { get; set; }
        public long Bar_Staff_Id { get; set; }
        public long Product_Id { get; set; }
        public int Batch_Id { get; set; }
        public int Qty { get; set; }
    
        public virtual BATCH BATCH { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual STAFF STAFF1 { get; set; }
    }
}
