//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_PRODUCT
    {
        public int Bar_Product_Id { get; set; }
        public long Product_Id { get; set; }
        public int Qty { get; set; }
        public bool Active { get; set; }
        public int Batch_Id { get; set; }
        public int Bar_Id { get; set; }
    
        public virtual BAR BAR { get; set; }
        public virtual BATCH BATCH { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
