//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH
    {
        public BATCH()
        {
            this.BAR_PRODUCT = new HashSet<BAR_PRODUCT>();
            this.BAR_SUPPLY_CATALOG = new HashSet<BAR_SUPPLY_CATALOG>();
            this.STOCK = new HashSet<STOCK>();
            this.STOCK_CATALOG = new HashSet<STOCK_CATALOG>();
        }
    
        public int Batch_Id { get; set; }
        public string Batch_Description { get; set; }
        public int Price_List_Id { get; set; }
        public int Qty { get; set; }
    
        public virtual ICollection<BAR_PRODUCT> BAR_PRODUCT { get; set; }
        public virtual ICollection<BAR_SUPPLY_CATALOG> BAR_SUPPLY_CATALOG { get; set; }
        public virtual PRICE_LIST PRICE_LIST { get; set; }
        public virtual ICollection<STOCK> STOCK { get; set; }
        public virtual ICollection<STOCK_CATALOG> STOCK_CATALOG { get; set; }
    }
}
