//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        public int Branch_Id { get; set; }
        public int Business_Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Email_address { get; set; }
        public string Phone_number { get; set; }
        public string Alternative_Phone { get; set; }
        public string Alternative_Email { get; set; }
    
        public virtual BUSINESS BUSINESS { get; set; }
    }
}
