//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET
    {
        public int Budget_Id { get; set; }
        public int Budget_No { get; set; }
        public string Budget_Item { get; set; }
        public bool Signed { get; set; }
        public System.DateTime Date { get; set; }
        public bool Delivered { get; set; }
        public long Generated_By_Staff_Id { get; set; }
        public long Signed_By_Staff_Id { get; set; }
    
        public virtual STAFF STAFF { get; set; }
        public virtual STAFF STAFF1 { get; set; }
    }
}
