//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS
    {
        public BUSINESS()
        {
            this.BRANCH = new HashSet<BRANCH>();
        }
    
        public int Business_Id { get; set; }
        public string Business_Name { get; set; }
        public string Logo_Url { get; set; }
    
        public virtual ICollection<BRANCH> BRANCH { get; set; }
    }
}
