//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.RESERVATION = new HashSet<RESERVATION>();
        }
    
        public long Person_Id { get; set; }
        public int Times_Visited { get; set; }
        public System.DateTime Last_Date_Visited { get; set; }
        public string Customer_Id { get; set; }
        public bool Active { get; set; }
        public Nullable<decimal> Maximum_Allowed_Credit { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<RESERVATION> RESERVATION { get; set; }
    }
}
