//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        public int Discount_Id { get; set; }
        public string Discount_Name { get; set; }
        public decimal Percentage_Off { get; set; }
        public string Description { get; set; }
    }
}
