//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAPPY_HOUR
    {
        public int Happy_Hour_Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public long Staff_Id { get; set; }
        public bool Activated { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
