//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.SALES = new HashSet<SALES>();
        }
    
        public long Order_Id { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Time_Order { get; set; }
        public Nullable<bool> Checked_Out { get; set; }
        public string Order_No { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> Product_Id { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ICollection<SALES> SALES { get; set; }
    }
}
