//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int Payment_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public long Staff_Id { get; set; }
        public int Payment_Type_id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Outstanding_Amount { get; set; }
        public string Order_No { get; set; }
        public bool Paid { get; set; }
        public System.DateTime Last_Update_Time { get; set; }
        public Nullable<System.DateTime> Expected_Payment_Date { get; set; }
        public decimal Amount_Tendered { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
