//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_LIST
    {
        public PRICE_LIST()
        {
            this.BATCH = new HashSet<BATCH>();
        }
    
        public int Price_List_Id { get; set; }
        public int Bar_Id { get; set; }
        public decimal Normal_Price { get; set; }
        public decimal Happy_Hour_Price { get; set; }
        public decimal Cost { get; set; }
    
        public virtual BAR BAR { get; set; }
        public virtual ICollection<BATCH> BATCH { get; set; }
    }
}
