//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_UNIT
    {
        public PRODUCT_UNIT()
        {
            this.CATALOG = new HashSet<CATALOG>();
        }
    
        public int Product_Unit_Id { get; set; }
        public long Product_Id { get; set; }
        public int Items { get; set; }
        public int Unit_Id { get; set; }
    
        public virtual ICollection<CATALOG> CATALOG { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
