//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELIGION
    {
        public RELIGION()
        {
            this.PERSON = new HashSet<PERSON>();
        }
    
        public int Religion_Id { get; set; }
        public string Religion_Name { get; set; }
    
        public virtual ICollection<PERSON> PERSON { get; set; }
    }
}
