//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int Reservation_Id { get; set; }
        public int Reservation_Type_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public System.DateTime Check_In { get; set; }
        public System.DateTime Check_Out { get; set; }
        public bool Is_Checked_Out { get; set; }
        public string Additional_Information { get; set; }
        public string Reservation_Code { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_address { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual RESERVATION_TYPE RESERVATION_TYPE { get; set; }
    }
}
