//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARY
    {
        public long Salary_Id { get; set; }
        public Nullable<decimal> Credit_Balance { get; set; }
        public Nullable<decimal> Unauthorised_Credit { get; set; }
        public Nullable<decimal> Staff_Credit { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<int> Attendance { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public long Staff_Id { get; set; }
        public string Month { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Final_Balance { get; set; }
        public decimal Salary1 { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
