//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARY_SCHEME
    {
        public int Salary_Scheme_Id { get; set; }
        public int Role_Id { get; set; }
        public decimal Basic_Salary_Amount { get; set; }
        public Nullable<decimal> Tax { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
