//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_TYPE
    {
        public SALES_TYPE()
        {
            this.SALES = new HashSet<SALES>();
        }
    
        public int Sales_Type_Id { get; set; }
        public string Sales_Type_Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SALES> SALES { get; set; }
    }
}
