//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES
    {
        public long Sales_Id { get; set; }
        public System.DateTime Date_Of_Transaction { get; set; }
        public int Sales_Type_Id { get; set; }
        public long Staff_Id { get; set; }
        public long Order_Id { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual SALES_TYPE SALES_TYPE { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
