//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.CATALOG = new HashSet<CATALOG>();
            this.HAPPY_HOUR = new HashSet<HAPPY_HOUR>();
            this.PAYMENT = new HashSet<PAYMENT>();
            this.SALARY1 = new HashSet<SALARY>();
            this.SALES = new HashSet<SALES>();
        }
    
        public long Staff_Id { get; set; }
        public long User_Id { get; set; }
        public string Account_Number { get; set; }
        public long Person_Id { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual ICollection<CATALOG> CATALOG { get; set; }
        public virtual ICollection<HAPPY_HOUR> HAPPY_HOUR { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<SALARY> SALARY1 { get; set; }
        public virtual ICollection<SALES> SALES { get; set; }
        public virtual USER USER { get; set; }
    }
}
