//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        public STATE()
        {
            this.LOCAL_GOVERNMENT = new HashSet<LOCAL_GOVERNMENT>();
            this.PERSON = new HashSet<PERSON>();
        }
    
        public string State_Id { get; set; }
        public string State_Name { get; set; }
        public int Nationality_Id { get; set; }
    
        public virtual ICollection<LOCAL_GOVERNMENT> LOCAL_GOVERNMENT { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
        public virtual ICollection<PERSON> PERSON { get; set; }
    }
}
