//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public int Stock_Id { get; set; }
        public long Product_Id { get; set; }
        public int Quantity_Left { get; set; }
        public System.DateTime Last_Update_Time { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
