//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CATALOG
    {
        public int Stock_Catlog_Id { get; set; }
        public long Staff_Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Supplier_Id { get; set; }
        public int Batch_Id { get; set; }
        public long Product_Id { get; set; }
        public string Receipt_number { get; set; }
    
        public virtual BATCH BATCH { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
