//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT
    {
        public UNIT()
        {
            this.PRODUCT_UNIT = new HashSet<PRODUCT_UNIT>();
        }
    
        public int Unit_Id { get; set; }
        public string Unit_Name { get; set; }
        public string Unit_Description { get; set; }
    
        public virtual ICollection<PRODUCT_UNIT> PRODUCT_UNIT { get; set; }
    }
}
