//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.STAFF = new HashSet<STAFF>();
        }
    
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Role_Id { get; set; }
        public Nullable<System.DateTime> Last_Login_Date { get; set; }
        public string Image_File_Url { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual ICollection<STAFF> STAFF { get; set; }
    }
}
