//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ACTIVITY_LOG
    {
        public long Product_Id { get; set; }
        public System.DateTime Date_Of_Transaction { get; set; }
        public int Stock_Type_Id { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public long Staff_Id { get; set; }
        public string Product_Name { get; set; }
        public string Supplier_Name { get; set; }
        public string Company_Name { get; set; }
        public string Stock_Type_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
    }
}
