//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progno.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAYMENT
    {
        public int Payment_Id { get; set; }
        public long User_Id { get; set; }
        public int Payment_Type_id { get; set; }
        public string Payment_Type_Name { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Outstanding_Amount { get; set; }
        public string Order_No { get; set; }
        public bool Paid { get; set; }
        public System.DateTime Last_Update_Time { get; set; }
        public Nullable<System.DateTime> Expected_Payment_Date { get; set; }
        public long Customer_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
    }
}
